
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 04 18:04:27 MST 2019
//----------------------------------------------------

package fuentes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMENTARIOS = 2;
  public static final int DEFECTO = 72;
  public static final int EINICIAL = 29;
  public static final int CONJUNTO = 15;
  public static final int MTABLA = 34;
  public static final int PYCOMA = 57;
  public static final int GRAFICO = 20;
  public static final int SI = 68;
  public static final int EFINAL = 30;
  public static final int ELEMENTOESTADO = 61;
  public static final int AFN = 28;
  public static final int OPRINPAL = 36;
  public static final int ELEMENTO = 60;
  public static final int SELEC = 70;
  public static final int POT = 11;
  public static final int POR = 9;
  public static final int AFD = 27;
  public static final int FUNCION = 24;
  public static final int VALIDAR = 25;
  public static final int PAR_C = 53;
  public static final int PAR_A = 52;
  public static final int NOT = 46;
  public static final int DEC = 49;
  public static final int DPUNTO = 58;
  public static final int AUTOMATA = 13;
  public static final int ER = 33;
  public static final int BOOLEANO = 14;
  public static final int OREXP = 8;
  public static final int BELOWE = 40;
  public static final int HACER = 67;
  public static final int PARA = 73;
  public static final int COMA = 56;
  public static final int ENTERO = 4;
  public static final int DETENER = 74;
  public static final int EQUAL = 41;
  public static final int ORDEN = 35;
  public static final int DECIMAL = 5;
  public static final int FIN = 18;
  public static final int HASTA = 65;
  public static final int DIV = 10;
  public static final int INT1 = 50;
  public static final int ABOVEE = 39;
  public static final int EXPRESION = 17;
  public static final int MENOS = 7;
  public static final int MAS = 6;
  public static final int NEQUAL = 42;
  public static final int EOF = 0;
  public static final int MIENTRAS = 64;
  public static final int MOSTRAR = 22;
  public static final int CHAR1 = 51;
  public static final int CON = 26;
  public static final int INI = 21;
  public static final int ABOVE = 37;
  public static final int TRANSICION = 31;
  public static final int INC = 48;
  public static final int BELOW = 38;
  public static final int LLAV_C = 55;
  public static final int LLAV_A = 54;
  public static final int OR = 43;
  public static final int error = 1;
  public static final int ENTER = 63;
  public static final int ID = 3;
  public static final int CONTINUA = 75;
  public static final int SINO = 69;
  public static final int ELEMENTOESTADO2 = 62;
  public static final int CASO = 71;
  public static final int HACIA = 32;
  public static final int FLOTANTE = 19;
  public static final int ASIG = 59;
  public static final int ESTADO = 16;
  public static final int ALFABETO = 12;
  public static final int AND = 44;
  public static final int NUEVO = 23;
  public static final int NAND = 47;
  public static final int XOR = 45;
  public static final int REPETIR = 66;
}

